---

core:
    num_workers: 50

logging:
    file: "nornir.log"
    
inventory: 
    options:
        host_file: "inventory/hosts.yaml"
        group_file: "inventory/groups.yaml"
        defaults_file: "inventory/defaults.yaml"
